CREATE TABLE syncotron_runs (
id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
name char(6) NOT NULL,
start_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
end_timestamp TIMESTAMP WITH TIME ZONE NOT NULL
);
