CREATE TABLE beamlines (
id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
name VARCHAR (50) UNIQUE NOT NULL,
acronym VARCHAR (8) NOT NULL,
old_acronym VARCHAR(8),
division VARCHAR (50) NOT NULL,
link VARCHAR (400) NOT NULL
);
