CREATE TABLE Beamlines (
id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
name VARCHAR (50) UNIQUE NOT NULL,
acronym VARCHAR (7) NOT NULL,
division VARCHAR (50) NOT NULL,
link VARCHAR (400) NOT NULL
);
