INSERT INTO bio_sample_type_origin_sub_origin_links (bio_sample_type_id, origin_id, sub_origin_id) VALUES
( (SELECT id FROM bio_sample_types WHERE type_name = 'Tissues'), (SELECT id FROM sample_origins WHERE name = 'Human'), (SELECT id FROM sample_sub_origins WHERE name = 'None') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Tissues'), (SELECT id FROM sample_origins WHERE name = 'Mouse'), (SELECT id FROM sample_sub_origins WHERE name = 'None') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Tissues'), (SELECT id FROM sample_origins WHERE name = 'Rat'), (SELECT id FROM sample_sub_origins WHERE name = 'None') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Tissues'), (SELECT id FROM sample_origins WHERE name = 'Dog'), (SELECT id FROM sample_sub_origins WHERE name = 'None') ),

( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Human'), (SELECT id FROM sample_sub_origins WHERE name = 'Blood Cells - Leukocytes') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Human'), (SELECT id FROM sample_sub_origins WHERE name = 'Blood Cells - Erythrocytes') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Human'), (SELECT id FROM sample_sub_origins WHERE name = 'Blood Cells - Thrombocytes') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Human'), (SELECT id FROM sample_sub_origins WHERE name = 'Stem Cells - Pluripotent') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Human'), (SELECT id FROM sample_sub_origins WHERE name = 'Stem Cells - Somatic') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Human'), (SELECT id FROM sample_sub_origins WHERE name = 'Stem Cells - Mesenchymal') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Human'), (SELECT id FROM sample_sub_origins WHERE name = 'Endothelial Cells') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Human'), (SELECT id FROM sample_sub_origins WHERE name = 'Nerve Cells') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Human'), (SELECT id FROM sample_sub_origins WHERE name = 'Endocrine Cells') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Human'), (SELECT id FROM sample_sub_origins WHERE name = 'Myocytes') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Human'), (SELECT id FROM sample_sub_origins WHERE name = 'Keratinocytes') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Human'), (SELECT id FROM sample_sub_origins WHERE name = 'Adipocytes') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Human'), (SELECT id FROM sample_sub_origins WHERE name = 'Osteocytes') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Human'), (SELECT id FROM sample_sub_origins WHERE name = 'Gametes - Egg Cell') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Human'), (SELECT id FROM sample_sub_origins WHERE name = 'Gametes - Sperm Cell') ),

( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Mouse'), (SELECT id FROM sample_sub_origins WHERE name = 'Blood Cells - Leukocytes') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Mouse'), (SELECT id FROM sample_sub_origins WHERE name = 'Blood Cells - Erythrocytes') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Mouse'), (SELECT id FROM sample_sub_origins WHERE name = 'Blood Cells - Thrombocytes') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Mouse'), (SELECT id FROM sample_sub_origins WHERE name = 'Stem Cells - Pluripotent') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Mouse'), (SELECT id FROM sample_sub_origins WHERE name = 'Stem Cells - Somatic') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Mouse'), (SELECT id FROM sample_sub_origins WHERE name = 'Stem Cells - Mesenchymal') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Mouse'), (SELECT id FROM sample_sub_origins WHERE name = 'Endothelial Cells') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Mouse'), (SELECT id FROM sample_sub_origins WHERE name = 'Nerve Cells') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Mouse'), (SELECT id FROM sample_sub_origins WHERE name = 'Endocrine Cells') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Mouse'), (SELECT id FROM sample_sub_origins WHERE name = 'Myocytes') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Mouse'), (SELECT id FROM sample_sub_origins WHERE name = 'Keratinocytes') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Mouse'), (SELECT id FROM sample_sub_origins WHERE name = 'Adipocytes') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Mouse'), (SELECT id FROM sample_sub_origins WHERE name = 'Osteocytes') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Mouse'), (SELECT id FROM sample_sub_origins WHERE name = 'Gametes - Egg Cell') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Mouse'), (SELECT id FROM sample_sub_origins WHERE name = 'Gametes - Sperm Cell') ),

( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Rat'), (SELECT id FROM sample_sub_origins WHERE name = 'Blood Cells - Leukocytes') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Rat'), (SELECT id FROM sample_sub_origins WHERE name = 'Blood Cells - Erythrocytes') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Rat'), (SELECT id FROM sample_sub_origins WHERE name = 'Blood Cells - Thrombocytes') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Rat'), (SELECT id FROM sample_sub_origins WHERE name = 'Stem Cells - Pluripotent') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Rat'), (SELECT id FROM sample_sub_origins WHERE name = 'Stem Cells - Somatic') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Rat'), (SELECT id FROM sample_sub_origins WHERE name = 'Stem Cells - Mesenchymal') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Rat'), (SELECT id FROM sample_sub_origins WHERE name = 'Endothelial Cells') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Rat'), (SELECT id FROM sample_sub_origins WHERE name = 'Nerve Cells') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Rat'), (SELECT id FROM sample_sub_origins WHERE name = 'Endocrine Cells') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Rat'), (SELECT id FROM sample_sub_origins WHERE name = 'Myocytes') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Rat'), (SELECT id FROM sample_sub_origins WHERE name = 'Keratinocytes') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Rat'), (SELECT id FROM sample_sub_origins WHERE name = 'Adipocytes') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Rat'), (SELECT id FROM sample_sub_origins WHERE name = 'Osteocytes') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Rat'), (SELECT id FROM sample_sub_origins WHERE name = 'Gametes - Egg Cell') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Rat'), (SELECT id FROM sample_sub_origins WHERE name = 'Gametes - Sperm Cell') ),

( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Dog'), (SELECT id FROM sample_sub_origins WHERE name = 'Blood Cells - Leukocytes') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Dog'), (SELECT id FROM sample_sub_origins WHERE name = 'Blood Cells - Erythrocytes') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Dog'), (SELECT id FROM sample_sub_origins WHERE name = 'Blood Cells - Thrombocytes') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Dog'), (SELECT id FROM sample_sub_origins WHERE name = 'Stem Cells - Pluripotent') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Dog'), (SELECT id FROM sample_sub_origins WHERE name = 'Stem Cells - Somatic') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Dog'), (SELECT id FROM sample_sub_origins WHERE name = 'Stem Cells - Mesenchymal') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Dog'), (SELECT id FROM sample_sub_origins WHERE name = 'Endothelial Cells') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Dog'), (SELECT id FROM sample_sub_origins WHERE name = 'Nerve Cells') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Dog'), (SELECT id FROM sample_sub_origins WHERE name = 'Endocrine Cells') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Dog'), (SELECT id FROM sample_sub_origins WHERE name = 'Myocytes') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Dog'), (SELECT id FROM sample_sub_origins WHERE name = 'Keratinocytes') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Dog'), (SELECT id FROM sample_sub_origins WHERE name = 'Adipocytes') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Dog'), (SELECT id FROM sample_sub_origins WHERE name = 'Osteocytes') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Dog'), (SELECT id FROM sample_sub_origins WHERE name = 'Gametes - Egg Cell') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Dog'), (SELECT id FROM sample_sub_origins WHERE name = 'Gametes - Sperm Cell') ),

( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Plants'), (SELECT id FROM sample_sub_origins WHERE name = 'Parenchyma Cells') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Plants'), (SELECT id FROM sample_sub_origins WHERE name = 'Collenchyma Cells') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Plants'), (SELECT id FROM sample_sub_origins WHERE name = 'Sclerenchyma Cells') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Plants'), (SELECT id FROM sample_sub_origins WHERE name = 'Xylem and Phloem Cells') ),

( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Fungi'), (SELECT id FROM sample_sub_origins WHERE name = 'Yeast') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Fungi'), (SELECT id FROM sample_sub_origins WHERE name = 'Molds(Hyphal Cells)') ),

( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Bacteria'), (SELECT id FROM sample_sub_origins WHERE name = 'Gram-positive') ),
( (SELECT id FROM bio_sample_types WHERE type_name = 'Cells'), (SELECT id FROM sample_origins WHERE name = 'Bacteria'), (SELECT id FROM sample_sub_origins WHERE name = 'Gram-negative') );
