INSERT INTO "BeamlineContacts" (user_id, beamline_id) VALUES 
((SELECT badge FROM "Users" WHERE username = 'blai'), (SELECT id FROM "Beamlines" WHERE acronym = '2-id-d')),
((SELECT badge FROM "Users" WHERE username = 'luxili'), (SELECT id FROM "Beamlines" WHERE acronym = '2-id-d')),
((SELECT badge FROM "Users" WHERE username = 'sichen'), (SELECT id FROM "Beamlines" WHERE acronym = '2-id-d')),
((SELECT badge FROM "Users" WHERE username = 'yluo89'), (SELECT id FROM "Beamlines" WHERE acronym = '2-id-d')),
((SELECT badge FROM "Users" WHERE username = 'emaxey'), (SELECT id FROM "Beamlines" WHERE acronym = '2-id-d')),
((SELECT badge FROM "Users" WHERE username = 'blai'), (SELECT id FROM "Beamlines" WHERE acronym = '2-id-e')),
((SELECT badge FROM "Users" WHERE username = 'luxili'), (SELECT id FROM "Beamlines" WHERE acronym = '2-id-e')),
((SELECT badge FROM "Users" WHERE username = 'oantipova'), (SELECT id FROM "Beamlines" WHERE acronym = '2-id-e')),
((SELECT badge FROM "Users" WHERE username = 'yluo89'), (SELECT id FROM "Beamlines" WHERE acronym = '2-id-e')),
((SELECT badge FROM "Users" WHERE username = 'blai'), (SELECT id FROM "Beamlines" WHERE acronym = '8-bm')),
((SELECT badge FROM "Users" WHERE username = 'emaxey'), (SELECT id FROM "Beamlines" WHERE acronym = '8-bm')),
((SELECT badge FROM "Users" WHERE username = 'qjin'), (SELECT id FROM "Beamlines" WHERE acronym = '8-bm')),
((SELECT badge FROM "Users" WHERE username = 'blai'), (SELECT id FROM "Beamlines" WHERE acronym = '19-id-e')),
((SELECT badge FROM "Users" WHERE username = 'maser'), (SELECT id FROM "Beamlines" WHERE acronym = '19-id-e')),
((SELECT badge FROM "Users" WHERE username = 'swieghold'), (SELECT id FROM "Beamlines" WHERE acronym = '19-id-e')),
((SELECT badge FROM "Users" WHERE username = 'mfrith'), (SELECT id FROM "Beamlines" WHERE acronym = '19-id-e')),
((SELECT badge FROM "Users" WHERE username = 'cai'), (SELECT id FROM "Beamlines" WHERE acronym = '19-id-e')),
((SELECT badge FROM "Users" WHERE username = 'mvholt'), (SELECT id FROM "Beamlines" WHERE acronym = '26-id-c')),
((SELECT badge FROM "Users" WHERE username = 'tzhou'), (SELECT id FROM "Beamlines" WHERE acronym = '26-id-c')),
((SELECT badge FROM "Users" WHERE username = 'cai'), (SELECT id FROM "Beamlines" WHERE acronym = '26-id-c')),
((SELECT badge FROM "Users" WHERE username = 'blai'), (SELECT id FROM "Beamlines" WHERE acronym = '33-id-c')),
((SELECT badge FROM "Users" WHERE username = 'vrose'), (SELECT id FROM "Beamlines" WHERE acronym = '33-id-c')),
((SELECT badge FROM "Users" WHERE username = 'junjingdeng'), (SELECT id FROM "Beamlines" WHERE acronym = '33-id-c'))
;
