DROP TABLE bio_samples CASCADE;
DROP TABLE bio_sample_type_origin_sub_origin_links CASCADE;
DROP TABLE bio_sample_conditions CASCADE;    
DROP TABLE bio_sample_fixations CASCADE;
DROP TABLE bio_sample_fixatives CASCADE;  
DROP TABLE bio_sample_types CASCADE;
DROP TABLE sample_origins CASCADE;
DROP TABLE sample_sources CASCADE;
DROP TABLE sample_sub_origins CASCADE;
