pub const KEY_BEAMLINE_AVAILABLE_SCANS: &str = "BEAMLINE_AVAILABLE_SCANS_";
pub const KEY_BEAMLINE_SCAN_LOGS: &str = "BEAMLINE_SCAN_LOGS_";
pub const KEY_TASK_QUEUE_WAITING: &str = "TASK_QUEUE_WAITING_";
pub const KEY_TASK_QUEUE_PROCESSING: &str = "TASK_QUEUE_PROCESSING_";
pub const KEY_TASK_QUEUE_DONE: &str = "TASK_QUEUE_DONE_";
pub const KEY_WORKER_HEARTBEAT: &str = "WORKER_HEARTBEAT_";
